# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         GearmanX-Starter
version:      0.05
version_from: lib/GearmanX/Starter.pm
installdirs:  site
requires:
    Gearman::XS:                   0.08
    Perl::Unsafe::Signals:         0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
