--- #YAML:1.0
name:               GearmanX-Starter
version:            0.03
abstract:           Start Gearman Workers
author:
    - Douglas Wilson <dougw@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Gearman::XS:          0.08
    Perl::Unsafe::Signals:  0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
